= Rancher Desktop as Docker Desktop alternative

You are a few steps far from moving away from Docker Desktop to a much more powerfull free alternative, which will enable you to introduce Kubernetes in your development environment if desired, or continue working as normal with plain Docker-like containers.

If you are new to containers or you are not already familiar with Docker, we encourage you to take some courses (like https://www.pluralsight.com/courses/getting-started-docker[this one]) or research on the web about Docker, which has been the most spread solution so far for containerization.

== Installation

The script `install.ps1` will install the Rancher Desktop application along with some extra tools:

* A tool to enable the usage when connected to a VPN.
* Docker binary for Windows containers.
* Activate the Containers Windows feature.
* A Powershell profile to be able to use Docker commands as usual.

To install this solution, you must clone the repository and run `install.ps1` with the desired flags as administrator. The extra tools developed are activated by adding some optional flags when executing the installer.

* Install the Rancher Desktop application alone:

`.\install.ps1`

* Install Rancher Desktop working with a VPN:

`.\install.ps1 -vpn`

* Install Rancher Desktop with Windows containers feature:

`.\install.ps1 -windows`

* Install Rancher Desktop with friendly alias:

`.\install.ps1 -alias`

* Install Rancher Desktop with all the extra tools:

`.\install.ps1 -vpn -windows -alias`

== Usage

Using Rancher Desktop is very simple, Rancher Desktop comes by default with containerd runtime, so if you install the standalone application or just the VPN function you will be able to execute all the Docker commands with:

`nerdctl <command>` or `nerdctl compose <command>`

If you add the Windows containers feature you can run both Linux and Windows containers without the need to change the daemon. Linux containers will work with `nerdctl` and `nerdctl compose`, and for Windows containers you can execute the following:

`docker --context win <command>` or `docker-compose --context win`

This new solution changes all the namings when executing Docker commands which will imply implay many changes on scripts and spend time in getting used to use Docker commands with this new names. To solve this you can execute the installer with the `-alias` flag. This flag will set the following alias:

* `docker` and `docker-compose` for `nerdctl` and `nerdctl compose` in order to work with Linux containers as usual.
* `dockerw` and `dockaerw-compose` for `docker --context win` and `docker-compose --context win` in order to work with Windows containers without needing to add the context flag everytime you want to execute a command.

== Uninstall

To uninstall Rancher Desktop and all the extra tools installed execute the script `uninstall.ps1` as administrator.

The uninstall script will cleanup the environment variables, folders and tools, leaving your computer as clean as it was before installing the solution.

== Extra features

Rancher Desktop comes with the option to enable Kubernetes in order to work with it in your local machine.

This feature comes disabled by default, but you are able to activate it by going into the Rancher Desktop app > Kubernetes Settings and click on `Enable Kubernetes` to start using it.